name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build_linux:
    name: Linux
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        config:
        - { name: "GCC", cc: gcc, cxx: g++ }
        - { name: "clang", cc: clang, cxx: clang++ }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
    - uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Update packages
      run: sudo apt-get update
    - name: Install dependencies
      run: |
        sudo apt-get install -qq libsdl2-dev libfreetype6 ninja-build
        pip3 install meson
    - name: Build
      run: bash scripts/create-appimage.sh v2.0
    - uses: actions/upload-artifact@v2
      with:
        name: AppImage
        path: LiteXL-v2.0-x86_64.AppImage
